services:
  app:
    image: ruancampelo/estudai-api:1
    build:
      context: .
    env_file:
      - .env
    ports:
      - "5112:5112"
    networks:
      - product_service_network
networks:
  product_service_network:
    driver: bridge

