services:
  app:
    image: ruancampelo/estudai-api:1
    build:
      context: .
    env_file:
      - .env
    volumes:
      - ${SSL_CERTIFICATE}:${SSL_CERTIFICATE}
      - ${SSL_CERTIFICATE_KEY}:${SSL_CERTIFICATE_KEY}
    ports:
      - "5112:5112"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: estudai
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

