services:
  app:
    image: ruancampelo/estudai-api:1
    build:
      context: .
    env_file:
      - .env
    ports:
      - "5112:5112"
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
