services:
  app:
    image: ruancampelo/estudai-api:1
    build:
      context: .
    env_file:
      - .env
    volumes:
      - ${SSL_KEY_HOST_PATH}:${SSL_KEY_CONTAINER_PATH}:ro
      - ${SSL_CERT_HOST_PATH}:${SSL_CERT_CONTAINER_PATH}:ro
    ports:
      - "5112:5112"
      - "443:443"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: estudai
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

