name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      run: go build -o estudai-api ./...

  deploy-docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: List files in the workspace
      run: ls -la

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v2
      with:
        images: |
          ruancampelo/estudai-api
          ghcr.io/${{ github.repository }}

    - name: Build and push Docker images
      id: push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ruancampelo/estudai-api:1
        labels: estudai-api
