name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      run: go build -v ./...

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Connect to Server and Run Docker Compose
      uses: appleboy/ssh-action@v0.1.0
      with:
        host: ${{ secrets.SSH_HOST }}          # O endereço IP ou domínio do servidor
        username: ${{ secrets.SSH_USERNAME }}   # O nome de usuário SSH
        key: ${{ secrets.SSH_PRIVATE_KEY }}      # A chave privada SSH
        script: |
          cd estudai
          git pull
          docker-compose up -d                    
